### PR TITLE
Switch to 'standard' linter

### PR DESCRIPTION
**Pull request by kasbah**
As mentioned in #7. Adapted lint script complains:

```
  ./example/clockblock.js:25:28: Missing space before function parentheses.
  ./example/clockblock.js:54:39: Missing space before function parentheses.
  ./example/clockblock.js:77:31: Missing space before function parentheses.
  ./example/clockblock.js:83:25: Missing space before function parentheses.
  ./example/clockblock.js:95:54: Missing space before function parentheses.
  ./example/clockblock.js:100:10: Closing curly brace does not appear on the same line as the subsequent block.
  ./integration/client.js:98:24: Missing space before function parentheses.
  ./integration/client.js:110:14: Missing space before function parentheses.
  ./integration/client.js:117:10: Closing curly brace does not appear on the same line as the subsequent block.
  ./integration/client.js:120:10: Closing curly brace does not appear on the same line as the subsequent block.
  ./integration/client.js:121:14: Multiple spaces found before 'body'.
  ./integration/server.js:21:32: Missing space before function parentheses.
  ./integration/server.js:24:38: Missing space before function parentheses.
  ./integration/server.js:36:65: Missing space before function parentheses.
  ./integration/server.js:48:35: Missing space before function parentheses.
  ./integration/server.js:71:20: Missing space before function parentheses.
  ./integration/server.js:77:55: Missing space before function parentheses.
  ./integration/server.js:88:22: Missing space before function parentheses.
  ./lib/_board-style.js:5:37: Missing space before function parentheses.
  ./lib/_board-style.js:16:50: Missing space before function parentheses.
  ./lib/_board-style.js:20:28: Missing space before function parentheses.
  ./lib/_gather-layers.js:8:24: Missing space before function parentheses.
  ./lib/_gather-layers.js:20:26: Missing space before function parentheses.
  ./lib/_gather-layers.js:29:29: Missing space before function parentheses.
  ./lib/_gather-layers.js:37:29: Missing space before function parentheses.
  ./lib/_gather-layers.js:45:10: Closing curly brace does not appear on the same line as the subsequent block.
  ./lib/_gather-layers.js:55:42: Missing space before function parentheses.
  ./lib/_gather-layers.js:63:36: Missing space before function parentheses.
  ./lib/_gather-layers.js:64:20: Missing space before function parentheses.
  ./lib/_gather-layers.js:87:10: Closing curly brace does not appear on the same line as the subsequent block.
  ./lib/index.js:13:29: Missing space before function parentheses.
  ./lib/index.js:35:43: Missing space before function parentheses.
  ./lib/index.js:42:31: Missing space before function parentheses.
  ./lib/index.js:48:1: More than 1 blank line not allowed.
  ./lib/index.js:60:31: Missing space before function parentheses.
  ./lib/index.js:66:28: Missing space before function parentheses.
  ./lib/index.js:78:41: Missing space before function parentheses.
  ./lib/index.js:88:31: Missing space before function parentheses.
  ./lib/sort-layers.js:4:37: Missing space before function parentheses.
  ./lib/sort-layers.js:5:32: Missing space before function parentheses.
  ./lib/sort-layers.js:14:10: Closing curly brace does not appear on the same line as the subsequent block.
  ./lib/sort-layers.js:17:10: Closing curly brace does not appear on the same line as the subsequent block.
  ./lib/sort-layers.js:27:12: Closing curly brace does not appear on the same line as the subsequent block.
  ./lib/stack-layers.js:8:27: Missing space before function parentheses.
  ./lib/stack-layers.js:20:24: Missing space before function parentheses.
  ./lib/stack-layers.js:36:26: Missing space before function parentheses.
  ./lib/stack-layers.js:50:24: Missing space before function parentheses.
  ./lib/stack-layers.js:51:37: Missing space before function parentheses.
  ./lib/stack-layers.js:63:26: Missing space before function parentheses.
  ./lib/stack-layers.js:92:28: Multiple spaces found before '{'.
  ./lib/wrap-layer.js:4:36: Missing space before function parentheses.
```

Do you want to switch to this style? 

EDIT: Also [checked in yarn.lock](https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control) as we are changing dependencies. Seems like good practice and should speed up Travis builds actually.

### CODE REVIEW

**Comment by kasbah** [comment]
I applied it with `--fix`. The only thing I don't like is the `else` on the same line as the `}` because I used to use that and found it can slow me down when I am debugging and commenting out conditions and blocks. But of course it's no biggie and the lack of a need for a config and the `--fix` command itself would be worth it.

**Comment by mcous** [comment]
Yeah my two problems with standard are the `else` alignment you mentioned and the space between `function` and the parentheses (though, to be fair, I'm coming around to the latter).

I agree, though, that the idea of not bothering with lint configuration anymore is a nice one. If we really get bothered by certain things, forking standard is an option. For now, though, I think this is a good move.

**Comment by kasbah** [comment]
Great! So this is OK to merge? Any comments on including `yarn.lock`?

**Comment by mcous** [comment]
Oh, didn't see that yarn.lock at the bottom of the diff there; thanks for pointing it out. I'm still on the fence about yarn, especially for libraries. Regardless, I don't think it belongs in this PR

**Comment by kasbah** [comment]
Sure sure, I removed the lock and rebased everything. Please press merge if everything looks ok. 

I am using yarn more and more just because it speeds things up but checking in the yarn.lock already resolved some CI build issues for me on Kitnic which was nice. It doesn't affect the users of your lib does it?

**Pull request merged**
